# Generated by Django 3.0.3 on 2020-02-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(default='A0001', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('brand', models.CharField(default='自有品牌', max_length=200)),
                ('image', models.CharField(default='', max_length=200)),
                ('image1', models.CharField(default='', max_length=200)),
                ('image2', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateTimeField(default='timezone.now')),
                ('abstract', models.CharField(default='', max_length=200)),
                ('stock', models.PositiveIntegerField(default='')),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
