# Generated by Django 3.1.4 on 2021-05-10 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(default=0)),
                ('BuyerName', models.CharField(max_length=200)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('email', models.CharField(default='', max_length=200)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('productsku', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NewTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('models_f', models.BigIntegerField()),
                ('bool_f', models.BooleanField()),
                ('date_f', models.DateField(auto_now=True)),
                ('char_f', models.CharField(max_length=20, unique=True)),
                ('datetime_f', models.DateTimeField(auto_now_add=True)),
                ('decimal_f', models.DecimalField(decimal_places=2, max_digits=10)),
                ('float_f', models.FloatField(null=True)),
                ('int_f', models.IntegerField(default=2010)),
                ('tesxt_f', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='A0001', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('brand', models.CharField(default='自有品牌', max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pid', models.PositiveIntegerField(default=0)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField()),
                ('page', models.PositiveIntegerField(default='0')),
                ('href', models.CharField(default='nourl', max_length=200)),
                ('imagelink', models.CharField(default='nourl', max_length=200)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='ShippingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippingAddress', models.CharField(max_length=200)),
                ('wayofShipping', models.CharField(max_length=200)),
                ('BuyerName', models.CharField(max_length=200)),
            ],
        ),
    ]
