# Generated by Django 3.0.3 on 2020-02-20 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name1',
            new_name='name',
        ),
    ]
