# Generated by Django 3.0.3 on 2020-03-23 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20200318_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='BuyerName',
            new_name='buyername',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='productName',
            new_name='productname',
        ),
        migrations.RenameField(
            model_name='shippingdetail',
            old_name='BuyerName',
            new_name='buyerName',
        ),
    ]
