# Generated by Django 3.0.3 on 2020-03-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20200323_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='totalprice',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='qty',
            new_name='totalqty',
        ),
    ]
