# Generated by Django 3.0.3 on 2020-02-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20200219_1657'),
        ('mainsite', '0003_auto_20200220_1349'),
    ]

    operations = [
    ]
