# Generated by Django 3.0.3 on 2020-02-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_merge_20200222_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productPrice', models.CharField(max_length=200)),
                ('BuyerName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippingAddress', models.CharField(max_length=200)),
                ('wayofShipping', models.CharField(max_length=200)),
                ('BuyerName', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='stock',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
