# Generated by Django 3.0.3 on 2020-02-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_newtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='product_category',
            new_name='sku',
        ),
    ]
