# Generated by Django 3.0.3 on 2020-02-22 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20200222_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='stock',
            new_name='qty',
        ),
        migrations.RemoveField(
            model_name='post',
            name='product_category',
        ),
    ]
