# Generated by Django 3.0.3 on 2020-02-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_auto_20200222_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='stock',
        ),
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=1),
        ),
    ]
