# Generated by Django 3.0.3 on 2020-02-23 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_auto_20200222_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='A0001', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('brand', models.CharField(default='自有品牌', max_length=200)),
                ('image', models.CharField(default='', max_length=200)),
                ('image1', models.CharField(default='', max_length=200)),
                ('image2', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('abstract', models.CharField(default='', max_length=200)),
                ('qty', models.PositiveIntegerField(default='')),
                ('price', models.PositiveIntegerField()),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=1)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
