# Generated by Django 3.0.3 on 2020-03-04 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_auto_20200223_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='abstract',
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cart',
            name='productsku',
            field=models.CharField(default='A0001', max_length=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='pid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
