# Generated by Django 3.0.3 on 2020-03-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_auto_20200304_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productsku',
            field=models.CharField(default='', max_length=200),
        ),
    ]
