# Generated by Django 3.0.3 on 2020-03-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_auto_20200303_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='productsku',
        ),
    ]
