# Generated by Django 3.0.3 on 2020-03-10 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_auto_20200304_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='productPrice',
            new_name='price',
        ),
    ]
