# Generated by Django 3.0.3 on 2020-03-03 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_remove_cart_productsku'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='productsku',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainsite.products'),
        ),
    ]
