# Generated by Django 3.0.3 on 2020-03-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_auto_20200310_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
