# Generated by Django 3.0.3 on 2020-03-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0018_auto_20200310_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(default='其他', max_length=200),
        ),
    ]
