# Generated by Django 3.0.3 on 2020-03-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0019_products_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='page',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
